### ISSUE TITLE
Missing OK, Retry, Cancel buttons. No way to leave camera.

### ISSUE THREAD

**Issue by PortableSlots** [myflashlab/barcode-ANE#1]
Tried with closeOnResultFounded true and false. No buttons show.
Could not find a way to close the camera.

Using iOS 8.3.

**Comment by myflashlab** [comment]
we are not able to duplicate this problem. to be able to help you more, please provide more information on how this is happening.

we have tested on iPhone 5 and iPhone 6 plus with iOS 8.3 both on 32-bit run and 64-bit and it's working as expected.

are you having the problem when running the demo project provided by us?

**Comment by PortableSlots** [comment]
Just tested it and your example also works on iOS, showing the cancel button as intended. My first test was done using Starling. The camera worked and detected QR codes but the cancel button won't show. 

I would guess that the absense of the button is related to the use of Stage3D. Is your ANE compatible with Stage3D applications?

**Comment by myflashlab** [comment]
I have a wild guess... is your Starling app in landscape mode? we will be uploading a new version soon anyway...
