### ISSUE TITLE
I need light :)

### ISSUE THREAD

**Issue by DezarM** [myflashlab/barcode-ANE#10]
Hi. I buy this ANE, but I have not received source.
Now i need light. How can I turn on the light?

**Comment by DezarM** [comment]
guys. I need flashlight on my scanner:)
how on/off this function?
i see on xml com_doitflash_barcode_preferences.xml
this 
    <ListPreference
        android:entries="@array/preferences_front_light_options"
        android:entryValues="@array/preferences_front_light_values"
        android:key="preferences_front_light_mode"
        android:defaultValue="OFF"
        android:title="@string/preferences_front_light_title"
        android:summary="@string/preferences_front_light_summary"/>

but change value   android:defaultValue don't work.

**Comment by myflashlab** [comment]
lights are not currently supported. but we will add it in future releases. Thanks.

**Comment by marvisais** [comment]
+1 !

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
