### ISSUE TITLE
Using Zxing library on iOS?

### ISSUE THREAD

**Issue by JBoye** [myflashlab/barcode-ANE#11]
I know this is a big request, but would it be possible to switch to the Zxing library on iOS? 

I've found that the Android version works much better on small codes than the iOS currently does.

I've tested laser engraved Data Matrix codes (like the one below)  on iPhone 6 & 6 Plus, iPod Touch 6th gen, iPad Air 2, iPad Mini 2, Nexus 5, Nexus 7 and OnePlus One. 

It works great on all Android Devices, but fails most of the time on iOS

![img_20160329_105005](https://cloud.githubusercontent.com/assets/5902488/14102863/5fda0424-f59d-11e5-866f-fd1d29341cc7.jpg)

**Comment by myflashlab** [comment]
Sorry, Zxing is no more supported on latest versions of iOS. to be able to support different barcodes, we needed to stick with the iOS built in libraries.
