### ISSUE TITLE
Portrait mode not working properly

### ISSUE THREAD

**Issue by gorjan** [myflashlab/barcode-ANE#12]
Hello, I have a problem with this extension working in portrait mode. My app is always in portrait mode. In the app descriptor I set AutoOrient to false.
I changed the following values (relating to the extension) from landscape to portrait.
```<uses-feature android:name="android.hardware.screen.portrait" />```
and
```<activity android:name="com.google.zxing.client.android.CaptureActivity" android:screenOrientation="portrait"```

I recorded a screen cast video so you can see what exactly is happening. Here is the [link](https://drive.google.com/file/d/0B_97B2gs38ZDMG9jTkY0V21jZGM/view?usp=sharing).

**Comment by myflashlab** [comment]
@gorjan we saw the screencasting you sent but unfortunaitly we can't duplicate the problem on our own devices here! it's working normally. please let me know what device you are testing with? and if you have tried it on other devices too? do you see the same problem on other devices too?

Also please send us a demo .apk to install and test locally. Thanks.

**Comment by savvie** [comment]
I had opened an activity on the same issue about a month ago, I have the exact same problem, my test was on Oneplus one, Samsung galaxy tab 3 8" and Samsung galaxy tab 2 7".

**Comment by gorjan** [comment]
No problem, here is the link to the archive containing the apk file and xml app descriptor(for reference).
[Download link](https://drive.google.com/file/d/0B_97B2gs38ZDZ0xRNkFOaWlfbjQ/view?usp=sharing)

**Comment by gorjan** [comment]
I have tested it on Samsung S4, Cyanogen android 6.0

**Comment by gorjan** [comment]
Any news on the issue?

**Comment by myflashlab** [comment]
We have ordered a new Android device with Android 6.0.1 just to test this as it's working fine on older Android versions. we will update you quickly when we did the tests on the new device.

**Comment by savvie** [comment]
How can you say it works fine on older devices, gorjan told you he's tested on a samsung galaxy s3 with android 4.3.Additionaly I have tested on devices with android 5.1.1 and 4.4.2 and it's not working. I think you should check your code, it turns the view in portrait mode but won't scan it until you have turned it to landscape. Could you please tell us on what devices and android version you have tested it on? Maybe we can each try to run our apps on those devices and see if they work?

**Comment by savvie** [comment]
Please add to the list of devices that we've tested on, a samsung galaxy tab s 8.4 with android 5.0.2. We have spotted another issue as well. While landscape can be used to scan the barcode it has to be turned landscape only 90 degrees clockwise and not the other way around. This is a big problem, especially for left hand users who tend to turn the device anti clockwise to scan.

**Comment by myflashlab** [comment]
we are not able to duplicate the problem on none of our tests. nexus 5x Android 6.0.1 - Huawei Android 4.0.1 - Sony Xperia z and z1 Android 5.1.1 and samsung galaxy tab 2 Android 4.0.3

Will you be able to test it on these devices?

**Comment by myflashlab** [comment]
> While landscape can be used to scan the barcode it has to be turned landscape only 90 degrees clockwise and not the other way around.

@savvie do you have this problem when testing with the demo .apk available in our GitHub repository too?

**Comment by gorjan** [comment]
I don't have problems with your test APK because the values in the xml descriptor are set for **landscape** mode, **not portrait**. My problem is that i wan't to scan a barcode while in portrait mode, and not to have to rotate the phone 90 degrees. My app is always in portrait mode, the autoOrient to false. So it is logical that when I open the scanner it will be oriented and work in portrait mode. Only the first of the two is true, the scanner opens in portrait mode, but it doesn't work in portrait mode, the phone has to be rotated 90 degrees(turning it to landscape) for it to scan successfully. You can see what I mean in the video screencast that I sent you([here](https://drive.google.com/file/d/0B_97B2gs38ZDMG9jTkY0V21jZGM/view?usp=sharing)).
Also I packaged the example code with the relevant values changed to **portrait** so you can test it([here](https://drive.google.com/file/d/0B_97B2gs38ZDZ0xRNkFOaWlfbjQ/view?usp=sharing)).
I also tested the app on Sony Z3 Compact, Android 5.1.1, and the same problem occurs.

**Comment by myflashlab** [comment]
We are considering a new version release on this. https://github.com/myflashlab/barcode-ANE/issues/23
