### ISSUE TITLE
import com.luaye.console.C

### ISSUE THREAD

**Issue by CScottie** [myflashlab/barcode-ANE#13]
unable to find???

Scene 1, Layer 'Layer 1', Frame 1, Line 3, Column 26	1172: Definition com.luaye.console:C could not be found.

**Comment by myflashlab** [comment]
try including the "com" folder to your project library path: https://github.com/myflashlab/barcode-ANE/tree/master/FD/src

**Comment by CScottie** [comment]
Lol yea I figured that out last night sorry about was a slilly mistake but
I got everything working :) thanks though
