### ISSUE TITLE
ANE barcode function open return false

### ISSUE THREAD

**Issue by franklzr** [myflashlab/barcode-ANE#14]
hi there

I am using ANE barcode in Flash CC

but when I execute the following code:
```actionscript
var _ex:Barcode=new Barcode();
info.text=""+_ex.open(null, File.applicationDirectory.resolvePath("com_doitflash_barcode_beep.mp3"), true, "back to The Air APP! :D");
```

the function  open  return false

please tell me how to do

thanks very much

**Comment by myflashlab** [comment]
if the ```open``` method returns ```false``` it means that your device Android SDK is lower than [SDK 15](http://developer.android.com/reference/android/os/Build.VERSION_CODES.html#ICE_CREAM_SANDWICH_MR1) you should have also used the ```if (_ex.isSupported())``` method before calling the ```open``` method.

Wait, is this happening on iOS or Android?

**Comment by franklzr** [comment]
thanks reply

I am using ANE in android

**Comment by franklzr** [comment]
hi there
BTW
my Android SDK is V20.0
and  _ex.isSurpported()  returns true

thank you

**Comment by myflashlab** [comment]
Let me guess, you are using the demo ANE with the demo notice dialog, right? and you are calling the ```open``` method, right after initializing the ANE. If my guess is correct, then you should NOT call the ```open``` method before you have hit the demo notice dialog.

> NOTICE: the demo ANE works only after you hit the "OK" button in the dialog which opens. in your tests make sure that you are NOT calling other ANE methods prior to hitting the "OK" button.

[as said here](https://github.com/myflashlab/barcode-ANE#demo-apk)

**Comment by franklzr** [comment]
thanks reply

I have bought a license

**Comment by myflashlab** [comment]
Are you able to run the demo .apk in your test device? https://github.com/myflashlab/barcode-ANE/tree/master/FD/dist

**Comment by franklzr** [comment]
no, I can not install demo.apk in my Samsung Note 4

**Comment by myflashlab** [comment]
If you are running the final ANE (not the demo) and ```_ex.isSupported()``` is returning true, there is no reason why ```open``` should return false! That is weird.

let's try this please:
1) do install the demo .apk linked above and run it and tell me if that works on your target device. (you need to have Adobe Air app installed for the demo ane to be installed)

2) tell me your target device Android version/SDK version

3) Are you having this problem on other test devices too?

**Comment by myflashlab** [comment]
We would appriciate an update on this issue. please let us know how it went and if I should close the ticket now?
