### ISSUE TITLE
App crashes on iOS 9 when settings > privacy > camera is turned off

### ISSUE THREAD

**Issue by ckpsde** [myflashlab/barcode-ANE#17]
The app crashes on iOS 9 when settings > privacy > camera is turned off. How can I catch this error and present the user a popup with a description how to change the privacy settings?

This is my code:

```actionscript
import com.myflashlab.air.extensions.barcode.Barcode;
import com.myflashlab.air.extensions.barcode.BarcodeEvent;

var _ex:Barcode = new Barcode();

function ScanCode(e:Event):void{
	MovieClip(root).Hinweis("Bitte warten", "Scanner wird gestartet.\nBitte warten...", "NoButton", "NoButton");
	if (_ex.isSupported()){
		_ex.open([Barcode.QR], File.applicationDirectory.resolvePath("com_doitflash_barcode_beep.mp3"), true, "Abbrechen");
		}
		else {
			MovieClip(root).Hinweis("Hinweis", "Bitte die Nutzung der Kamera erlauben.", "NoID", "NoButton");
		}
	} else {
		MovieClip(root).Hinweis("Hinweis", "Ihr Telefon wird nicht unterstützt", "NoID", "NoButton");
	}
}

function onScanCancel(e:BarcodeEvent):void {
	MovieClip(root).Hinweis("Hinweis", "Der Scan wurde abgebrochen.", "NoID", "NoButton");
}
function onScanResult(e:BarcodeEvent):void { ...... }
_ex					.addEventListener(BarcodeEvent.RESULT, onScanResult);
_ex					.addEventListener(BarcodeEvent.CANCEL, onScanCancel);
```

**Comment by myflashlab** [comment]
Thanks for reporting this. I will put this on the board so the iOS team will add this feature a.s.a.p.

**Comment by myflashlab** [comment]
Alright, here are the latest news about this. please read the post here: http://www.myflashlabs.com/understanding-android-ios-permissions-in-adobe-air-apps/

Which explains everything you would need regarding permissions and how they should be handled in iOS and Android.

I should thank you for bringing this up. No ANE provider had seriously thought of this before and your report, made us do a detailed study on how permissions work on iOS and Android 6. The results are described in the post linked above. I am closing this ticket now, but feel free to ask any questions you might have.
