### ISSUE TITLE
Position the preview

### ISSUE THREAD

**Issue by varadig** [myflashlab/barcode-ANE#20]
There is a solution to position/resize the preview window, like the zbar ANE?
https://github.com/saumitrabhave/qr-zbar-ane

In the ZBar ANE , when startPreview, I can pass the viewport parameter (x,y,w,h).

thanks

**Comment by varadig** [comment]
Anybody???

**Comment by wigginsray** [comment]
Any update on this item. It would be very helpful to be able to have the preview are in a viewport - or at the very least, be able to edit the appearance of the "return" button or overlay display objects. My project is specifically for IOS (iPad) -  but I'm sure many have the same desire.

**Comment by varadig** [comment]
use zbar-ane instead of barcode-ANE was my solution

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
