### ISSUE TITLE
Front and Back Camera on tablet's switching

### ISSUE THREAD

**Issue by educatic** [myflashlab/barcode-ANE#21]
Hi, is there a way to set barcode-ANE to use the front camera on IOS and Android tablets. It default's to the back camera.

**Comment by eternaldb** [comment]
plus one for this feature

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
