### ISSUE TITLE
Barcode-ANE : Vertical orientation and camera square resizing

### ISSUE THREAD

**Issue by rafaelblanco00** [myflashlab/barcode-ANE#23]
hi, i have several days trying to make this work and have no goal yet.

How can i make the orientation of the camera view turn into vertical and how can make the rectangular frame get into a square shape .. couse if i want to scan just QR codes .. there is no need to the camera view to be rectangular ... any help???? ...

**Comment by myflashlab** [comment]
You may try changing this property: https://github.com/myflashlab/barcode-ANE/blob/master/FD/application.xml#L48

**Comment by rafaelblanco00** [comment]
i allready did it, the problem is that the rectangular shape, still reaminds the same way, i need it as square, and the red line is ok but the camera image get distort, en a vertical direction, i just add the ane in the way you specify, then change the line you ask me to change, and still work in that way, can you send me a flash as3 - air file, with the implementation that you say works for you? ... in which the camera orientation remaind vetical and with a square shape ?? .. in others hands .. why do you put both examples in the web site of the barcode ane, couse we have to guess how that  kind of properties works couse you web site does nos offer information about, i dowload and try what you have now, and it works but in a  horizontal way, but .. why your web site does not put an example of the vertical inplementation ??? ... right now i need to buy two licenses but i can not do it couse of this .. sorry my inglish ...

**Comment by myflashlab** [comment]
Aha, I see. the zxing library used on the Android side is actually having trouble on vertical views and makes the rectangle stretched a bit. I am now marking this issue so we can start a new version upgrade with the latest release of the library. Hopefully the vertical problem will be fixed. Nonetheless, from experience, we've seen that most users are preferring horizontal scan over vertical.

**Comment by rafaelblanco00** [comment]
mnn.. ok, so i will wait for the update, i think it is ok but, as a graphic designer ... i feel a restriction on that issue, both orientation have to be support correctly couse in my case, it is uncortable to try to read a qrcode with one hand, and it is not right after creating a vertical layout, and after searching and realise that YOUR ANE  is the only one on the market and looks nice and special ... have that restriction. so can i get informed whe this update get released?? .. couse afeter that i will buy. thanks! ... post: i am encurage people at my work to use this ANE, i really think is good.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
