### ISSUE TITLE
App closes

### ISSUE THREAD

**Issue by jamesgomes** [myflashlab/barcode-ANE#25]
We use the ANE in three different devices;
Zenfone 2: Android 5.0, it worked perfectly.
LG K130F: Android 5.1, it worked perfectly.
Moto X (1st Generation): Android 5.1, application close to open the QRCODE.

We are using the paid version.
Will you guys help us?

Thank you.

James Gomes

**Comment by myflashlab** [comment]
We don't have a moto X device! however, please connect your device to your computer while the Android Studio logcat window is open. Then try to create the crash and as soon as you see the crash report, send us the logs. maybe we can see in more details what could have gone wrong.

**Comment by myflashlab** [comment]
This issue has been inactive for a long time so I am closing it now. If anything, leave a message and I will re-open it.
