### ISSUE TITLE
create customized "Cancel" button on camera view

### ISSUE THREAD

**Issue by mc3dev** [myflashlab/barcode-ANE#26]
Is there a way to create a customized Cancel/Return button when the scanner/camera is on instead of using the "CancelBtnLabel" in the open() method?

**Comment by myflashlab** [comment]
I just marked this feature as an enhancement. Maybe we would consider developing a custom solution for the buttons. But currently, the button is a simple one like what you see.

**Comment by mc3dev** [comment]
Thanks for adding this to the enhancement. It will be very helpful if the button can be customized to specific needs.

**Comment by Barney4242** [comment]
Hi! 
Is there any update regarding this issue? =)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
