### ISSUE TITLE
Errors when test published with Flash Pro CC 2015 / AIR for iOS 18.0

### ISSUE THREAD

**Issue by mc3user** [myflashlab/barcode-ANE#3]
Hi, 
I created a new file with Flash Pro CC 2015, added the ANE to the Flash file, copied the code in AS3 API to the Flash file, then published with AIR for iOS 18.0. I got the error message below. Could you please advice what I should do? Thank you very much for your help.

ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.doitflash.air.extensions.barcode.android::Android()
	at com.doitflash.air.extensions.barcode::Barcode()
	at barcode_fla::MainTimeline/frame1()[barcode_fla.MainTimeline::frame1:4]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by myflashlab** [comment]
@mc3user your error log shows that the extension is not correctly embeded into your project. (this extension works with flash CC with no problem.)

**Comment by mc3user** [comment]
I embeded the extension like how I embeded other ANE in Flash CC 2015 and compiled it. 

I tried again and during the test movie in Flash it still displayed the same error message. 

The app publish process did not give any error but the app is just a black screen after it displayed a popup with "QR-code DEMO 
You are using a demo version of this extension!"
After the popup is closed. nothing happened.

I don't know how else I may embed an ANE. Please provide any feedback if possible. Thanks again for your help.

**Comment by myflashlab** [comment]
You are not running your test on FlashCC simulator, are you? If you are
having this issue, please send me a demo project to check more...

On Wednesday, July 15, 2015, mc3user <notifications@github.com> wrote:

> I embeded the extension like how I embeded other ANE in Flash CC 2015 and
> compiled it.
>
> I tried again and during the test movie in Flash it still displayed the
> same error message.
>
> The app publish process did not give any error but the app is just a black
> screen after it displayed a popup with "QR-code DEMO
> You are using a demo version of this extension!"
> After the popup is closed. nothing happened.
>
> I don't know how else I may embed an ANE. Please provide any feedback if
> possible. Thanks again for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/barcode-ANE/issues/3#issuecomment-121658790>
> .
>


-- 
Sent from iPhone

**Comment by mc3user** [comment]
The test movie uses the Flash CC mobile simulator. Attached is the test files. I appreciated your help on this.

**Comment by myflashlab** [comment]
I'm not at the office right now but you just said what the problem is. As I
guessed, you are running on a simulator. That's the problem. For the camera
to open, you must run it on a real device.

On Wednesday, July 15, 2015, mc3user <notifications@github.com> wrote:

> The test movie uses the Flash CC mobile simulator. Attached is the test
> files. I appreciated your help on this.
>
>
> From: myflashlab [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Wednesday, July 15, 2015 11:55 AM
> To: myflashlab/barcode-ANE
> Cc: Yu-Chang Fu
> Subject: Re: [barcode-ANE] Errors when test published with Flash Pro CC
> 2015 / AIR for iOS 18.0 (#3)
>
> You are not running your test on FlashCC simulator, are you? If you are
> having this issue, please send me a demo project to check more...
>
> On Wednesday, July 15, 2015, mc3user <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');><mailto:
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>> wrote:
>
> > I embeded the extension like how I embeded other ANE in Flash CC 2015
> and
> > compiled it.
> >
> > I tried again and during the test movie in Flash it still displayed the
> > same error message.
> >
> > The app publish process did not give any error but the app is just a
> black
> > screen after it displayed a popup with "QR-code DEMO
> > You are using a demo version of this extension!"
> > After the popup is closed. nothing happened.
> >
> > I don't know how else I may embed an ANE. Please provide any feedback if
> > possible. Thanks again for your help.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/myflashlab/barcode-ANE/issues/3#issuecomment-121658790>
>
> > .
> >
>
>
> --
> Sent from iPhone
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/myflashlab/barcode-ANE/issues/3#issuecomment-121659680>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/barcode-ANE/issues/3#issuecomment-121664343>
> .
>


-- 
Sent from iPhone

**Comment by mc3user** [comment]
I did published the IPA and ran on the iPad. After the popup message “"QR-code DEMO. You are using a demo version of this extension!" displayed, the camera did not come up and it remains as a black screen…


Thanks,
Yu-Chang
Skyp#: 484-252-2942
