### ISSUE TITLE
App is in portrait, when I start scanning it turns to landscape

### ISSUE THREAD

**Issue by PippoFlash** [myflashlab/barcode-ANE#31]
My app is in portrait mode. When I start scanning, the screen animates as if it switches to landscape. Scanning works, or I cancel, and then it animates back to portrait. This happens even if I hold device firmly in portrait mode.

**Comment by PippoFlash** [comment]
Anyway great ANE, works beautifully.

**Comment by myflashlab** [comment]
It's designed to be scanning in landscape mode which is easier for user experience. However, you may change this by modifying the following parameter in the manifest file ```android:screenOrientation="landscape"``` Doing that may make your screen look a bit stretched as using the scanner in landscape mode has been on focus.

**Comment by PippoFlash** [comment]
Thanks, it worked nicely. Yes image a bit stretched but better than seeing the screen rotate in a portrait only app.

**Comment by funkypaul** [comment]
Even when setting these values:
`                <uses-feature android:name="android.hardware.screen.portrait" />`

`                                android:screenOrientation="portrait"`

And having the scanning looking correctly in portrait mode, the scan doesnt work. When having the scanner in portrait I have to rotate my phone by 90degrees (the app is still in potrait) and then it reads the barcode correctly. Its like the looks are portrait but functionality is landscape, Maybe Im missing something?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
