### ISSUE TITLE
Barcode ANE (Android+iOS) V3.2 can not open scanner in Android

### ISSUE THREAD

**Issue by franklzr** [myflashlab/barcode-ANE#32]
hi there

I have bought a Barcode ANE (Android+iOS) early.
when I installed your original theApp.apk, it works OK.

I build a project with Adobe Flash CC 2015, I published a apk and installed it in my Samsung Note 4 mobile phone.
But I can not open Scanner, and it always display " isSurpported: false " in my screen of mobile phone.

please feel free to visit my html for detail of project, the address is below:
http://yottatech.cn/barcode/myquest.html

thanks a lot

Liu ZhiRong
2016.11.17.

**Comment by myflashlab** [comment]
What Android version you are running your app on? the min Android version to support this ANE is Android API 15

**Comment by rodolphonascimento** [comment]
I'm with same problem. How can i fix it? My Android device is 4.2.2 and so SDK 17.

**Comment by myflashlab** [comment]
this post might be helpful https://github.com/myflashlab/barcode-ANE/issues/35#issuecomment-287020322

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
