### ISSUE TITLE
Error occurred while packaging the application:

### ISSUE THREAD

**Issue by kryrnrj** [myflashlab/barcode-ANE#33]
Hi, I,'m going to buy your barcode-ane. But first i wanted to try. I'm using Flash Builder 4.7. But I get this error.
Thanks.

Error occurred while packaging the application:
aapt tool failed:Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
C:\Users\kryrnrj\AppData\Local\Temp\3205e7ee-fb09-4226-92e0-141c6296a981\AndroidManifest.xml:77: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.Transparent').

<android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	<uses-permission android:name="android.permission.INTERNET" />
		
	
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-feature android:name="android.hardware.camera" />
	<uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
	<uses-feature android:name="android.hardware.screen.landscape" />
	
	
	<uses-permission android:name="android.permission.VIBRATE"/>
	
	
	<uses-sdk android:minSdkVersion="15" />
	
	
	<uses-sdk android:targetSdkVersion="23"/>
	
	
	<supports-screens 	android:anyDensity="true" 
						android:largeScreens="true" 
						android:normalScreens="true" 
						android:smallScreens="true" 
						android:xlargeScreens="true" />
		
	<application>
		
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
		
		
		<activity 	android:name="com.google.zxing.client.android.CaptureActivity" 
					android:clearTaskOnLaunch="true" 
					android:screenOrientation="portrait" 
					android:configChanges="orientation|keyboardHidden" 
					android:stateNotNeeded="true" 
					android:theme="@android:style/Theme.NoTitleBar.Fullscreen" 
					android:windowSoftInputMode="stateAlwaysHidden" />
		
		
		<activity 	android:name="com.doitflash.barcode.utils.ExBridge" 
					android:theme="@style/Theme.Transparent" />
		
	</application>
</manifest>]]></manifestAdditions>
  </android>

**Comment by myflashlab** [comment]
are you using AIR SDK 24? If not try that and let us know.
