### ISSUE TITLE
debug in iOS

### ISSUE THREAD

**Issue by leefj** [myflashlab/barcode-ANE#34]
when i click "start scaner" the app screen is all white. what is wrong ?

**Comment by leefj** [comment]
is anyone there ?  no respond?

**Comment by myflashlab** [comment]
That would be great if you can provide us with more information, like, what is your AIR SDK? Are you seeing this always on all your test devices? what iOS versions have you tested this on? Are you using Starling? When you first tried to open the camera, did the iOS asked you for a camera access permission? if so, did you allow that? (we have a [permission check ANE](https://github.com/myflashlab/PermissionCheck-ANE/) for this reason) And moreover, connect your device to xcode and send us the possible error logs.

**Comment by leefj** [comment]
it seems really has error

`Date/Time:       2016-12-22 10:02:27 +0800
OS Version:      iPhone OS 10.1.1 (Build 14B150)
Architecture:    arm64
Report Version:  19

Command:         MainFinal
Path:            /var/containers/Bundle/Application/223152F9-38C1-486E-A254-2024362DCFA4/MainFinal.app/MainFinal
Version:         0.0.0 (0.0.0)
Parent:          launchd [1]
PID:             3577

Event:           wakeups
Wakeups:         45051 wakeups over the last 43 seconds (1043 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Duration:        43.20s
Steps:           24

Hardware model:  iPhone7,1
Active cpus:     2


Powerstats for:  MainFinal [3577]
UUID:            43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3
Start time:      2016-12-22 10:02:58 +0800
End time:        2016-12-22 10:03:09 +0800
Parent:          launchd
Microstackshots: 24 samples (100%)
Primary state:   8 samples Frontmost App, Kernel mode, Thread QoS Default
User Activity:   0 samples Idle, 24 samples Active
Power Source:    0 samples on Battery, 24 samples on AC
  14 start + 4 (libdyld.dylib + 17848) [0x18c3185b8]
    14 ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 1047696) [0x1001dfc90]
      14 UIApplicationMain + 208 (UIKit + 483380) [0x19331b034]
        14 -[UIApplication _run] + 684 (UIKit + 504572) [0x1933202fc]
          14 GSEventRunModal + 180 (GraphicsServices + 49560) [0x18edba198]
            14 CFRunLoopRunSpecific + 444 (CoreFoundation + 36936) [0x18d334048]
              10 __CFRunLoopRun + 1840 (CoreFoundation + 895948) [0x18d405bcc]
                10 __CFRunLoopDoSource1 + 436 (CoreFoundation + 905448) [0x18d4080e8]
                  10 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56 (CoreFoundation + 907572) [0x18d408934]
                    10 __CFMachPortPerform + 180 (CoreFoundation + 808300) [0x18d3f056c]
                      10 IODispatchCalloutFromCFMessage + 372 (IOKit + 24888) [0x18d6c7138]
                        4  IOMobileFramebufferVsyncNotifyFunc + 72 (IOMobileFramebuffer + 24788) [0x18fa100d4]
                          4  iomfb_GetMachMessageCount + 68 (IOMobileFramebuffer + 24928) [0x18fa10160]
                            4  _kernelrpc_mach_port_get_attributes + 140 (libsystem_kernel.dylib + 12128) [0x18c40df60]
                              4  mach_msg_trap + 8 (libsystem_kernel.dylib + 4460) [0x18c40c16c]
                                4  <Thread QoS User Interactive>
                        4  CA::Display::DisplayLink::dispatch_items + 444 (QuartzCore + 45160) [0x190667068]
                          4  CA::Display::DisplayLinkItem::dispatch + 44 (QuartzCore + 45500) [0x1906671bc]
                            4  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 112456) [0x1000fb748]
                              4  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 883136) [0x1001b79c0]
                                4  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 880536) [0x1001b6f98]
                                  4  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 2657392) [0x100368c70]
                                    2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 37328) [0x1000e91d0]
                                      2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 35508) [0x1000e8ab4]
                                        2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 5547224) [0x10062a4d8]
                                          2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 5643228) [0x100641bdc]
                                            2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 5545104) [0x100629c90]
                                              2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 5477504) [0x100619480]
                                                2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 5477916) [0x10061961c]
                                                  2  <User mode, Thread QoS User Interactive>
                                    2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 37132) [0x1000e910c]
                                      2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 36360) [0x1000e8e08]
                                        2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 32112) [0x1000e7d70]
                                          2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 33068) [0x1000e812c]
                                            2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 5914184) [0x100683e48]
                                              2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 6280152) [0x1006dd3d8]
                                                2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 6279364) [0x1006dd0c4]
                                                  2  <Thread QoS User Interactive>
                        2  CA::Display::DisplayLink::dispatch_items + 228 (QuartzCore + 44944) [0x190666f90]
                          2  <User mode, Thread QoS User Interactive>
              2  CFAbsoluteTimeGetCurrent + 0 (CoreFoundation + 36168) [0x18d333d48]
                2  <User mode, Thread QoS User Interactive>
              2  __CFRunLoopRun + 1456 (CoreFoundation + 895564) [0x18d405a4c]
                2  __CFRunLoopDoObservers + 108 (CoreFoundation + 893700) [0x18d405304]
                  2  CFArrayGetCount + 36 (CoreFoundation + 34672) [0x18d333770]
                    2  <User mode, Thread QoS User Interactive>
  10 _pthread_start + 284 (libsystem_pthread.dylib + 14176) [0x18c4f0760]
    10 _pthread_body + 240 (libsystem_pthread.dylib + 14416) [0x18c4f0850]
      10 ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 2996548) [0x1003bb944]
        10 ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 2997348) [0x1003bbc64]
          10 ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 2997252) [0x1003bbc04]
            6  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 1403532) [0x100236a8c]
              6  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 2996660) [0x1003bb9b4]
                6  __semwait_signal + 8 (libsystem_kernel.dylib + 127764) [0x18c42a314]
            4  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 1403524) [0x100236a84]
              4  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 1403692) [0x100236b2c]
                2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 3005600) [0x1003bdca0]
                  2  getsockopt + 8 (libsystem_kernel.dylib + 22136) [0x18c410678]
                2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 3005628) [0x1003bdcbc]
                  2  ??? (<43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3> + 3001052) [0x1003bcadc]
                    2  _platform_memset + 184 (libsystem_platform.dylib + 8680) [0x18c4e81e8]
                      2  <User mode>

  Binary Images:
         0x1000e0000 -                ???  ??? <43CB74CB-2D89-35E8-973E-DD4E7CBDD6B3>
         0x18c314000 -        0x18c31bfff  libdyld.dylib <39AAA2DB-E1A1-313C-9C83-8CC0268A2EA0> /usr/lib/system/libdyld.dylib
         0x18c40b000 -        0x18c432fff  libsystem_kernel.dylib <3BB31DBC-9985-3FA4-B33F-4948C9E2AF64> /usr/lib/system/libsystem_kernel.dylib
         0x18c4e6000 -        0x18c4edfff  libsystem_platform.dylib <14630F9A-4281-3C0A-8197-64B8ADA8383B> /usr/lib/system/libsystem_platform.dylib
         0x18c4ed000 -        0x18c4f8fff  libsystem_pthread.dylib <548D3D6A-3B57-38F2-820E-0382C8D77C0E> /usr/lib/system/libsystem_pthread.dylib
         0x18d32b000 -        0x18d6aefff  com.apple.CoreFoundation 6.9 (1348) <D72E357F-5B33-37AA-9693-522564A6032E> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
         0x18d6c1000 -        0x18d73cfff  com.apple.framework.IOKit 2.0.2 <97DF8046-F49D-3A3C-9A28-AD1C89EC90A9> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
         0x18edae000 -        0x18edc5fff  com.apple.GraphicsServices 1.0 (1.0) <6D8EC4C7-41AE-3332-AE48-54A3C69F9C68> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
         0x18fa0a000 -        0x18fa11fff  com.apple.IOMobileFramebuffer 250.1.1 (250.1.1) <2355C7F4-D2A2-31E4-BE5D-5B373305DA9D> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
         0x19065c000 -        0x190837fff  com.apple.QuartzCore 1.11 (449.40.9) <BF63FBA9-5947-3E54-8ED5-F6E4DB40E3AE> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
         0x1932a5000 -        0x194034fff  com.apple.UIKit 1.0 (1000) <7EF942F4-3C3E-3E4A-A6CE-C127B68ECBAB> /System/Library/Frameworks/UIKit.framework/UIKit
`

**Comment by leefj** [comment]
i use air 24.0.0.180 , iphone6 plus,ios 10.1; no starling ,just your demo code class named "MainFinal",
just copy from your example.

**Comment by myflashlab** [comment]
xcode log does not sound very helpful. Please send us your demo project you're working on (do not include the licenced ANEs) so we can run your project and see what happens.

**Comment by leefj** [comment]
this is my demo 
[demo.zip](https://github.com/myflashlab/barcode-ANE/files/668488/demo.zip)

**Comment by myflashlab** [comment]
I downloaded the files but please be very careful when sending files. in my last comment I did mention **(do not include the licensed ANEs)**. Please familiarize yourself with the privacy/policy rules here: http://www.myflashlabs.com/licensing/

Anyway, we'll check the files and let you know.

**Comment by myflashlab** [comment]
We tried to import the project into FB but it's not importing!

**Comment by eternaldb** [comment]
I also have the same problem.  When you close the app and open again, you see a flash of what is supposed to be on the screen, the back button and a view through the camera but then goes back to white.
[FD.zip](https://github.com/myflashlab/barcode-ANE/files/696363/FD.zip)

**Comment by eternaldb** [comment]
It works fine in adhoc mode so at least I can test and create a final product.

**Comment by myflashlab** [comment]
This seems to be happening on random cases in debug builds which is now fixed with the release of V3.3.0. Update yourself and it will be fine.
