### ISSUE TITLE
Error: Android camera encountered a problem

### ISSUE THREAD

**Issue by divlaine** [myflashlab/barcode-ANE#35]
Im trying your free demo apk.
But when i press "open scanner" im getting an alert with message "Sorry, the Android camera encountered a problem. You may need to restart the device".
Restarting device doesn't help."
ANE Implementation in my project also didnt work. Alert with demo text and that's all.

Android Sozy Z2.
airSDK 22

**Comment by funkypaul** [comment]
I have the same issue on Android 6.0.1, AIR SDK 24
When setting
<uses-sdk android:targetSdkVersion="23"/>
I have: 

 "Sorry, the Android camera encountered a problem. You may need to restart the device"

Changing to:
<uses-sdk android:targetSdkVersion="22"/>

Fixed the issue, why?

**Comment by myflashlab** [comment]
You need to be very careful with Android permissions. Read here for more information: https://github.com/myflashlab/barcode-ANE#permissions

You may also fine the following articles very helpful to get yourself familiar with Android permissions:
http://www.myflashlabs.com/adobe-air-app-permissions-android-ios/  
http://www.myflashlabs.com/understanding-android-ios-permissions-in-adobe-air-apps/

**Comment by iwebnetid** [comment]
make permission to camera hardware you made search google how to ask permission to camera
