### ISSUE TITLE
Activating/exiting scanner, triggers application SLEEP/WAKE events

### ISSUE THREAD

**Issue by PippoFlash** [myflashlab/barcode-ANE#37]
Starting and terminating scanner, triggers NativeApplication Event.DEACTIVATE/Event.ACTIVATE. This interferes with management of application modes.

**Comment by myflashlab** [comment]
This happens on the Android side, right? well, That's how Android works. When a new Activity starts, the AIR activity will stop. You need to manage your app logic based on this fact. There is no way we can prevent that.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
