### ISSUE TITLE
Beep sound - still can't get working

### ISSUE THREAD

**Issue by aeyachts99** [myflashlab/barcode-ANE#38]
I still can't get the beep sound to work although the vibration alert does work.

 I've followed the TODO comment (TODO: Known bug on ios: the beep mp3 file must be in the same folder where the main Adobe Air .swf file is.) and placed the sound file in my bin directory (where the swf is located), I'm using Intellij on a Mac. I have also tried packaging the sound file into the app file (.ipa).

AIR 24 SDK

**Comment by myflashlab** [comment]
While you are making sure that the beep mp3 file is packaged in your app (you can make sure of this by extracting the built .ipa file and see if the beep sound is there at the root of your application file), you also need to address the file like ```File.applicationDirectory.resolvePath("your_beep_sound.mp3")```

**Comment by aeyachts99** [comment]
How do I "extract" the .ipa file to check the sound file is being packaged?

I am addressing the file like this:
 _barcodeScan.open([Barcode.CODE128], File.applicationDirectory.resolvePath("com_doitflash_barcode_beep.mp3"), true, "CANCEL");

**Comment by myflashlab** [comment]
Well, rename the .ipa file to .zip and then look inside. Also, use the .exist() method on the sound File object and see if the file really exists or not.

**Comment by aeyachts99** [comment]
Renaming the .ipa suffix to .zip and then opening it gives a folder called 'Payload' with just a single file inside with the same name as the .ipa/app.

The File.exists property returns true.

 var sound:File = File.applicationDirectory.resolvePath("com_doitflash_barcode_beep.mp3");
                trace('sound.exists: ' + sound.exists); // true

**Comment by myflashlab** [comment]
>> trace('sound.exists: ' + sound.exists); // true

means that the file exists.

>> it gives a folder called 'Payload' with just a single file inside with the same name as the .ipa/app.

of course it does! go deep inside a little more and you must see your beep sound there.

If it is there, then I can't think of anything else unless you send us some xcode log files that might be helpful... Maybe the mp3 file cannot be read? try to use the mp3 sample file we have and see how it goes.

**Comment by aeyachts99** [comment]
I can see the .mp3 file in the package and it is your sample one I am using (which plays independently in iTunes so I think the file is OK).
I'll investigate the logs for some cause.

**Comment by aeyachts99** [comment]
I now have some console logs produced using the Console app in macOS sierra as per this article (https://www.malhal.com/2017/01/06/xcode-8-ios-10-non-stop-device-logs/) which I can send to you if you let ma have a contact point.

However, I did notice these lines in the log file (the app is titled AE Assets) which, I think show an error with playing the sound:

debug	09:30:47.511841 +0100	AE Assets	Resource lookup at <private>
	Request       : com_doitflash_barcode_beep type: mp3
	Result        : file:///var/containers/Bundle/Application/95ABCAA3-75B1-4FBC-8C8C-0035C1F3B561/AE%20Assets.app/com_doitflash_barcode_beep.mp3
default	09:30:47.512048 +0100	AE Assets	BarcodeANE|||ViewControllerBarcode|||loadBeepSound started: /var/containers/Bundle/Application/95ABCAA3-75B1-4FBC-8C8C-0035C1F3B561/AE Assets.app/com_doitflash_barcode_beep.mp3
debug	09:30:47.512209 +0100	AE Assets	Bundle: <private>, key: NSOSStatusErrorDomain, value: NSOSStatusErrorDomain, table: Error, localizationName: (null), result: OSStatus
debug	09:30:47.512379 +0100	AE Assets	Bundle: <private>, key: The operation couldn\U2019t be completed. (%@ error %ld.), value: The operation couldn\U2019t be completed. (%@ error %ld.), table: Error, localizationName: (null), result: The operation couldn’t be completed. (%1$@ error %2$ld.)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
