### ISSUE TITLE
Can't instantiate Barcode

### ISSUE THREAD

**Issue by Kodiakkb** [myflashlab/barcode-ANE#4]
I'd love to buy your extension but I can get it to work in my project.

I copied as much as I could form the exBarcode to my project (code, manifest) and I get this error when I instantiate a new Barcode() on Android 4.1.1:
 `Error #1009: Cannot access a property or method of a null object reference.`
I am able to compile, launch and use exBarcode on the same environment.

Since the ANE is not in debug mode I can hardly give you more details about it. I compile with AIR16 (but I use the same to compile exBarcode).
Here is the only visible object I have when my debugger stops on `new Barcode()`

    this : com.doitflash.air.extensions.barcode.android.Android {
	_cancel : "CANCEL" 
	closeOnResultFounded : true 
	_closeOnResultFounded : true 
	_context : null 
	_detectTypes : Array 
	_isSupported : false 
	_label : "" 
	_main : com.doitflash.air.extensions.barcode.Barcode {
		closeOnResultFounded : "TypeError: Error #1010: A term is undefined and has no properties." 
		context : null 
		_context : null 
		_launcher :  
		os : "android" 
		_os : "android" 
	}
	_ok : "OK" 
	_rescan : "RESCAN" 
    }

**Comment by myflashlab** [comment]
Since the context is null, it means that the extension is not properly
embeded into your project. Make sure you are doing everything correctly by
comparing your project settings with the demo project of ours. One usual
problem is about the manifest which you must change "air.com.doitflash...."
To your own package name.

On Friday, August 14, 2015, Kodiakkb <notifications@github.com> wrote:

> I'd love to buy your extension but I can get it to work in my project.
>
> I copied as much as I could form the exBarcode to my project (code,
> manifest) and I get this error when I instantiate a new Barcode() on
> Android 4.1.1:
> Error #1009: Cannot access a property or method of a null object reference.
> I am able to compile, launch and use exBarcode on the same environment.
>
> Since the ANE is not in debug mode I can hardly give you more details
> about it. I compile with AIR16 (but I use the same to compile exBarcode).
> Here is the only visible object I have when my debugger stops on new
> Barcode()
>
> this : com.doitflash.air.extensions.barcode.android.Android {
> _cancel : "CANCEL"
> closeOnResultFounded : true
> _closeOnResultFounded : true
> _context : null
> _detectTypes : Array
> _isSupported : false
> _label : ""
> _main : com.doitflash.air.extensions.barcode.Barcode {
>     closeOnResultFounded : "TypeError: Error #1010: A term is undefined and has no properties."
>     context : null
>     _context : null
>     _launcher :
>     os : "android"
>     _os : "android"
> }
> _ok : "OK"
> _rescan : "RESCAN"
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/barcode-ANE/issues/4>.
>


-- 
Sent from iPhone

**Comment by Kodiakkb** [comment]
Thank you for your time!
I read about this problem and had checked for it before... Do I have to change "com.doitflash.barcode.MainActivity" as well?

I use FD, the ANE is added to "SWC libraries", I right-clicked and checked "Add to Library". In your exBarcode, there are many other libraries I can't find in the lib folder (AIR3Extension, StageWebViewBridge...), and Vibration is referenced in Classpaths. Do I need any of them?

**Comment by myflashlab** [comment]
No, you just need to change anything that begins with
"air.com.doitflash....". And besides adding the ane to library which is a
must, you also need to add the ane into the manifest xml file... You should
be able to compile it fine, just take your time and compare the two
projects...

On Friday, August 14, 2015, Kodiakkb <notifications@github.com> wrote:

> Thank you for your time!
> I read about this problem and had checked for it before... Do I have to
> change "com.doitflash.barcode.MainActivity" as well?
>
> I use FD, the ANE is added to "SWC libraries", I right-clicked and checked
> "Add to Library". In your exBarcode, there are many other libraries I can't
> find in the lib folder (AIR3Extension, StageWebViewBridge...), and
> Vibration is referenced in Classpaths. Do I need any of them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/barcode-ANE/issues/4#issuecomment-131149523>
> .
>


-- 
Sent from iPhone

**Comment by Kodiakkb** [comment]
OK, I'm sorry, the mistake must be here but I don't get exactly what you mean.
Suppose my app id is "toto". What should I write instead of

	android:name="air.com.doitflash.exBarcode"
	android:name="com.doitflash.barcode.MainActivity"
	<extensionID>com.doitflash.air.extensions.barcode</extensionID>
?
Thank you again

**Comment by myflashlab** [comment]
You just beed to replace any "air.com.doitflash.exBarcode" with "air.toto".

On Friday, August 14, 2015, Kodiakkb <notifications@github.com> wrote:

> OK, I'm sorry, the mistake must be here but I don't get exactly what you
> mean.
> Suppose my app id is "toto". What should I write instead of
>
> android:name="air.com.doitflash.exBarcode"
> android:name="com.doitflash.barcode.MainActivity"
> <extensionID>com.doitflash.air.extensions.barcode</extensionID>
>
> ?
> Thank you again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/barcode-ANE/issues/4#issuecomment-131157689>
> .
>


-- 
Sent from iPhone

**Comment by Kodiakkb** [comment]
Fine, that's just the first one then!
Now I get "An implementation for native extension 'com.doitflash.air.extensions.barcode' required by the application was not found for the target platform." It's a bit better, I'll look into it on my own.
Thanks!

**Comment by myflashlab** [comment]
you are still missing ```<extensionID>com.doitflash.air.extensions.barcode</extensionID>``` look at https://github.com/myflashlab/barcode-ANE/blob/master/FD/application.xml

**Comment by Kodiakkb** [comment]
No, it is in the application.xml, I did copy it from the example.
This solved the problem: https://plus.google.com/u/0/+PhilippeElsass/posts/7rhFEX7S372

**Comment by myflashlab** [comment]
Would you please mention which part exactly solved your problem? so this ticket will help others too...

**Comment by Kodiakkb** [comment]
Setting the ANE as external and appending to the the adt call line.

**Comment by myflashlab** [comment]
good. I hope you will enjoy the extension :)
