### ISSUE TITLE
<manifestAdditions> code causes error

### ISSUE THREAD

**Issue by douglasmccarroll** [myflashlab/barcode-ANE#40]
Hi,

When I add the following XML to <manifestAdditions>, as per your instructions...

`<activity
   android:name="com.doitflash.barcode.utils.ExBridge"
   android:theme="@style/Theme.Transparent" />  `                      

... I get the error below.

None of the other XML that you specify creates a problem, just this one chunk. If it's there, the error occurs. If I comment it out, the error doesn't occur.

Thanks,

Douglas

aapt tool failed:Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
/var/folders/s1/c9d2g57923b27_pd4yxg4t_c0000gn/T/554b7e7c-1df7-442a-9d85-be8e318a88ef/AndroidManifest.xml:81: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.Transparent').

ADT command line:
/Applications/IntelliJ IDEA 2016.3.app/Contents/jdk/Contents/Home/jre/bin/java -Dapplication.home=/Users/douglasmccarroll/_apps/flex_4_15_0_air_23 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx2048m -jar /Users/douglasmccarroll/_apps/flex_4_15_0_air_23/lib/adt.jar -package -target apk-debug -listen 7936 -storetype PKCS12 -keystore /Applications/IntelliJ IDEA 2016.3.app/Contents/plugins/flex/lib/temp_keystore.p12 -storepass keystore_password /Users/douglasmccarroll/_src/dev/langmentor_out/LangMentor.apk /Users/douglasmccarroll/_src/dev/langmentor_out/langmentor_android-app.xml -extdir /Users/douglasmccarroll/_src/dev/lib/native_extensions -C /Users/douglasmccarroll/_src/dev/langmentor_out langmentor_android.swf -C /Users/douglasmccarroll/_src/dev/langmentor/assets_langmentor_android assets -C /Users/douglasmccarroll/_src/dev/langmentor/src_langmentor_assets .

**Comment by myflashlab** [comment]
Such error messages usually happen if you are using old AIR SDKs or you are using a shared build where you should try building in captive mode. Moreover, you need to make sure the dependency ANEs are all embedded in the project. Often intelliJ users are having trouble with embedding ANEs correctly. As a final hint, also make sure you are using the latest version of the ANE and the dependency files.

**Comment by douglasmccarroll** [comment]
Hi,

Thanks for your response.


> Such error messages usually happen if you are using old AIR SDKs 

I've now tried this with both AIR 24 and AIR 25


> or you are using a shared build where you should try building in captive mode

In my IntelliJ build configuration I have 'Framework linkage' set to 'Default (Mergeded into code)'

I assume that this is what you're talking about, and that I have this set correctly.


> Moreover, you need to make sure the dependency ANEs are all embedded in the project. 
> Often intelliJ users are having trouble with embedding ANEs correctly

My embedding approach is working with another ANE, i.e. there are no problems when I build, and the ANE's functionality works, so I don't think that this is the problem.


> make sure you are using the latest version of the ANE and the dependency files

I've now made sure of this.


And yet, I still get the same error.


I've done a fair amount of Googling, and have found other responses (some by you) that indicate that the problem in these cases is that two different ANE's have JAR files that conflict.

So I've tried removing every ANE from my app-xml, and every ANE reference from my code, and have unembedded every ANE in my project.

And yet I still get this the error messages if this block of code is in my app-xml...

  <activity
    android:name="com.doitflash.barcode.utils.ExBridge"
    android:theme="@style/Theme.Transparent" />
    
... and I don't get the error if it's not there.

Actually, I also don't get the error if I remove android:theme="@style/Theme.Transparent" from that block. 

This is interesting...  

So my next step is to re-enable all of my ANEs - in my app-xml, re-embedding the ANEs, uncommenting ANE usage in code - but leaving this one 'Transparent' line out. When I deploy this version onto my Android phone everything works fine, except that the barcode scanner looks distinctly strange ... in fact it looks as though it's missing some 'transparency'...   :)   and it doesn't recognize a QR code when I try to scan it.

I'm not sure what all this points to ... but I'm hoping that you will be able to take this info and glean some insight that you can share...

Thanks,

Douglas

**Comment by douglasmccarroll** [comment]
Hi,

Some more info...

First, I have a correction:

In my previous post I wrote:

>> or you are using a shared build where you should try building in captive mode
> In my IntelliJ build configuration I have 'Framework linkage' set to 'Default (Merged into code)'
> I assume that this is what you're talking about, and that I have this set correctly.

I now realize that this isn't what you are referring to. You're talking about building with a captive AIR runtime, whereas the setting that I referred to controls to how the Flex framework is linked into the code.

Second, it looks as though I'm not building with a captive runtime because I'm doing USB debugging, and when one builds a debug version of an AIR app one _cannot_ use a captive runtime.

(See https://youtrack.jetbrains.com/issue/IDEA-75620: "when creating package for debugging - captive runtime is not allowed")

When I build a 'release' version of my app (using Build > Package AIR Application in IntelliJ) the "AndroidManifest.xml already defines" error doesn't occur.

So it looks as though the fact that I'm not using a captive runtime is indeed the problem.

But this creates a new problem. I need to be able to debug my AIR app. One cannot debug with a captive runtime. And I can't include the 'Transparent' setting in my app XML without a captive runtime. 

Thus I can't debug a properly configured version of my app?

If your ANE will only work in captive mode, how can I debug my app if I'm using your ANE?

Thanks,

Douglas

**Comment by douglasmccarroll** [comment]
Yet another update...

I just re-read my initial post, and my previous comment, and realized that GitHub has removed the XML I included in my posts.

It looks as though I need to use the 'Insert Code' tool to include XML in a post.

Here's the XML:

`  <activity
    android:name="com.doitflash.barcode.utils.ExBridge"
    android:theme="@style/Theme.Transparent" />`

It is the 'theme=Transparent' line that is causing the problem. (The 'name=ExBridge' line doesn't cause any problem.)

**Comment by myflashlab** [comment]
I'm not sure about ```IntelliJ``` as we don't use it but we know that using other IDEs like FlashBuilder, FlashCC or FlashDevelop, you can build captive apk files in debug mode. Other developers using IntelliJ however never reported a problem before with debugging thing.

The manifest settings should work fine if applied like [the sample](https://github.com/myflashlab/barcode-ANE#air-xml-manifest) Are you sure you are using the latest AIR SDK and have you targeted the latest SDK in your manifest like [this](https://github.com/myflashlab/barcode-ANE/blob/master/FD/application.xml#L2)?

**Comment by douglasmccarroll** [comment]
> using other IDEs like FlashBuilder, FlashCC or FlashDevelop, 
> you can build captive apk files in debug mode. Other developers
> using IntelliJ however never reported a problem before with 
> debugging thing.

Yes. It turns out that, at least for recent versions of the AIR SDK, the runtime is _always_ captive. See this conversation:

https://forums.adobe.com/thread/2308812

So that theory of mine was clearly wrong. Now I'm back to wondering why this would happen when I debug but not when I create a release version.

**Comment by douglasmccarroll** [comment]
Also worth noting: It looks as though the barcode reader works fine without the 'Transparent' line in the XML. Does this line actually do anything important? Might it be a good idea to take it out of your example XML? In any case, removing it completely seems to be working as a solution for my problem, so it probably isn't a good use of time for us to keep thinking about the question of why this line creates a problem for me in debug mode and not in release mode. Thanks for your help with this issue.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
