### ISSUE TITLE
com.myflashlab.air.extensions.barcode::Barcode/isSupported()

### ISSUE THREAD

**Issue by gersonmontenegro** [myflashlab/barcode-ANE#42]
Hi. I tried to implement the ANE in my Flash Builder project, but I got this error. 

```
TypeError: Error #1010: A term is undefined and has no properties.
	at com.myflashlab.air.extensions.barcode::Barcode/isSupported()
```

The application indeed is going ok until the line when the "isSupported" method is called:

```
			this._ex = new Barcode();
			this._ex.addEventListener(BarcodeEvent.RESULT, this.onResult);
			this._ex.addEventListener(BarcodeEvent.CANCEL, this.onCancel);
			
			if(this._ex.isSupported()){
```

¿any idea? . Thanks

**Comment by gersonmontenegro** [comment]
Hi. I debugged the app directly on the Android phone and the error is not showing up anymore, but, now, the _isSupported()_ method give a _false_ as a result. What that mean?

Thanks

**Comment by myflashlab** [comment]
1. is this happening on Android? or iOS?
2. Are you using the latest AIR SDK? please do!
2. This ANE needs camera permission. have you implemented the permissionCheck ANE? read here https://github.com/myflashlab/barcode-ANE#permissions

**Comment by gersonmontenegro** [comment]
Thanks for reply.

1. For now, only Android. I didn't use iOS.
2. I'm using Feathers SDK. My current Feathers SDK use AIR 23
3. The Camera permission exist

**Comment by gersonmontenegro** [comment]
Hi. I updated feathers and now I'm using SDK 24, but problems still are here...

I tried to use PermissionCheck ANE, but it doesn't work properly and I don't know what it is

Here is the most suspected option that I have
![image](https://user-images.githubusercontent.com/3643808/27364765-22e694ee-5602-11e7-83c2-73b90418c6f9.png)
And yes, there is a render problem too with the checkboxes, but it doesn't matter. I can't add all the ANE's in my project.
finally, the project run, but there is an error :
![image](https://user-images.githubusercontent.com/3643808/27364819-64aa3ac0-5602-11e7-8171-4b0203568d96.png)
The manifest has the respectively extension:
`<extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>`

...Do I have missed something? . Thanks.

**Comment by myflashlab** [comment]
Well, on FlashBuilder, just adding the ANE into the manifest is not enough. you also need to package them... maybe watch these videos (one of them is using FlashBuilder) https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

Besides that, make sure you are adding the camera permission tags to the manifest also. use this sample manifest: https://github.com/myflashlab/barcode-ANE/blob/master/FD/application.xml

Let us know how you are doing.

**Comment by gersonmontenegro** [comment]
Hi. I saw the videos before started, and I made every step, but there is still something wrong :(

I removed all ANE and I added again, but, the barcodeExtension and the permissionCheck seems there are not compatible, because I can't add both at the same time. Always I got this:

![image](https://user-images.githubusercontent.com/3643808/27387013-1faa60b6-565d-11e7-9c44-2aaf3ee70d7a.png)

So, in execution time I got this error:
`Main Thread (Suspended: VerifyError: Error #1014: Class com.myflashlab.air.extensions.nativePermissions::PermissionCheck could not be found.)	
`
What might cause it?. Thanks.

**Comment by gersonmontenegro** [comment]
I put the same manifest from https://github.com/myflashlab/barcode-ANE/blob/master/FD/application.xml , and at least the application is execute, but the permission doesn't allow me use the camera, but I thing the package system is the cause, so, I can't include permissionChek and barcodeExt at the same same. ¿Any idea?. Thanks

**Comment by myflashlab** [comment]
That red warning you are seeing in FlashBuilder is just fine and you can simply ignore it. Just make sure you are packaging the ANEs in your app. these ANEs definitely don't conflict with each other.

Anyway, can you prepare a simple demo project (do NOT include the ANEs in your package) and send it to us here so we can test run your setup and spot the problem?

**Comment by gersonmontenegro** [comment]
I tried again all from 0, but nothing seems working. I'm about to give up, but I wanna make my app in AS3. 

I run `permission.request(PermissionCheck.SOURCE_CAMERA, this.onRequestPermission);`, and the result is always 0. What that mean?

When the line `var permissionState:int = permission.check(PermissionCheck.SOURCE_CAMERA);` is executed, the result is 0 too, and thats the value for PermissionCheck.PERMISSION_OS_ERR, and I don't know what to do now.

I send my Feathers project with the minimum code possible. I use the latest Feathers, and the feathers.swc is attached in this message
[feathers.swc.zip](https://github.com/myflashlab/barcode-ANE/files/1095553/feathers.swc.zip)
[barcodeFeathers.zip](https://github.com/myflashlab/barcode-ANE/files/1095530/barcodeFeathers.zip)

I'll be pending for a reply. Thanks.

**Comment by myflashlab** [comment]
Hmm, we have difficulties running your project, it would help if you send a pure AS3 project with minimal code. Anyhow, First things first, if ```permission.check``` returns ```0``` it means there's something wrong in the setup of the permission ANE. Are you sure you are using the latest version of AndroidSupport ANE? V25.3.1 is the latest one and you should use at least AIR SDK 25.

If you are sure, please send us a pure AS3 project with minimum permissionCheck code. Let's try to fix that first.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
