### ISSUE TITLE
android app crashes after first QRScan

### ISSUE THREAD

**Issue by gerardvde** [myflashlab/barcode-ANE#43]
[testscanner.zip](https://github.com/myflashlab/barcode-ANE/files/1141401/testscanner.zip)
After successfully scanning a QRCode , a second or third scan crashes the app (no ui response)
compiled with SDK26 with permissionsCheck ANE (shows GRANTED in Debugger)
Tested on a Samsung GT-P3110 Android 4.1.2
Attached a test fla

**Comment by gerardvde** [comment]
iOS working fine Android app crashes after one or two times
Without Android support I want my money back!

**Comment by myflashlab** [comment]
Please send us the following information:

1. your demo .apk which you are experiencing the problem with.
2. AndroidStudio logcat stacks when the error happens.

Also tell us if you are seeing this only on the mentioned device? or does it happen on other devices you have tested on also?

**Comment by gerardvde** [comment]
[TestQRScanner.zip](https://github.com/myflashlab/barcode-ANE/files/1164657/TestQRScanner.zip)
It also happened on other Android devices

**Comment by myflashlab** [comment]
I ran your .apk and it's not asking for camera permission! the error message in logcat AndroidStudio is:

```
Unexpected error initializing camera
java.lang.RuntimeException: Fail to connect to camera service
```
As [descibed](https://github.com/myflashlab/barcode-ANE#permissions), you need to ask users for camera access before opening it.

Then, I manually activated the camera and your sample apk is working just fine!

**Comment by gerardvde** [comment]
in my code I _ex.request(PermissionCheck.SOURCE_CAMERA, onRequestResult); 
this does not ask the user for permission but does return GRANTED, one scan succeeds and then the app crashes

**Comment by myflashlab** [comment]
If it returns GRANTED, it means that your app had asked for this permission before. So, as long as you can open the camera, it's ok. Anyhow, we tried on a few different deveice, they worked fine. 

I guess, you should send us AndroidStudio logcat stacks when the crash happens so we can check what could have gone wrong. As far as I see, the app is working fine (if the camera permission is granted)

**Comment by gerardvde** [comment]
You were abled to scan a barcode more than two times ? I managed two scans at the most

**Comment by myflashlab** [comment]
Yes, we scanned successfully several times.

**Comment by gerardvde** [comment]
Ok I will  download Android Studio to get the log cat stacks

**Comment by gerardvde** [comment]
I downgraded my app to SDK23 works perfect on IOS9 and IOS11 , only Android does not compile with SD23 due to the androidSupport.ane which throws this error (error goes away when I remove the ane)

aapt tool failed:/private/var/folders/y1/5fm14vw95p59ffk7lhkpdmk80000gn/T/ced15922-c866-44a4-8d5c-bd28fb512076/android.support.v7.appcompat-res/values-v23/values-v23.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

/private/var/folders/y1/5fm14vw95p59ffk7lhkpdmk80000gn/T/ced15922-c866-44a4-8d5c-bd28fb512076/android.support.v7.appcompat-res/values-v23/values-v23.xml:34: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

/private/var/folders/y1/5fm14vw95p59ffk7lhkpdmk80000gn/T/ced15922-c866-44a4-8d5c-bd28fb512076/android.support.v7.appcompat-res/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/private/var/folders/y1/5fm14vw95p59ffk7lhkpdmk80000gn/T/ced15922-c866-44a4-8d5c-bd28fb512076/android.support.v7.appcompat-res/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

**Comment by gerardvde** [comment]
demo.apk runs fine on my device, still trying to find the cause of the crahse of my app, one scan succeeds then it crashes

**Comment by gerardvde** [comment]
compiled your demo with SDK 26 and it ran on my device
Changed this line of code in my app:
		_barcodeReader.open( [Barcode.QR], null, true, 'Abbrechen' );
to
		_barcodeReader.open( null, null, true, 'Abbrechen' );
Now it scans multiple times without crashing
