### ISSUE TITLE
demo.apk missing

### ISSUE THREAD

**Issue by gerardvde** [myflashlab/barcode-ANE#44]
Tried to download the demo.apk, 404!

**Comment by myflashlab** [comment]
Try this link:
https://github.com/myflashlab/barcode-ANE/tree/badd4ec4cc8a552968b4b70d4d3782543a3c146f/FD/dist

**Comment by myflashlab** [comment]
plz let us know if you are experiencing the same problem as https://github.com/myflashlab/barcode-ANE/issues/43 with the demo .apk also?

**Comment by myflashlab** [comment]
you may also find the latest apk here: https://github.com/myflashlab/barcode-ANE/blob/master/demo.apk
