### ISSUE TITLE
Barcode scanner initial slow when upgrade androidSupport.ane to V25.3.1

### ISSUE THREAD

**Issue by hengway1989** [myflashlab/barcode-ANE#45]
Hi, as subject, please help advice. If I downgrade androidSupport to 23.4.0, it will be a lot faster. The different can be up to 5 seconds. Thank you

**Comment by hengway1989** [comment]
Hi, can please help have a look on this issue?

**Comment by myflashlab** [comment]
Are you experiencing this on all your test devices?

**Comment by hengway1989** [comment]
Yes, I tested on Samsung note 5, lenovo tab 3 730X, mipad 1, and Lenovo Phab, all facing this issue, but once I downgrade androidSupport to 23.4.0 then it will be faster. Please check, thank you

**Comment by myflashlab** [comment]
This information must help you with this problem. https://github.com/myflashlab/common-dependencies-ANE/tree/master/androidSupport

**Comment by myflashlab** [comment]
let us know if this works for the problem?

**Comment by hengway1989** [comment]
Sorry for late reply, and when I change to androidSupport-lite.ane, it show error below:
Error occurred while packaging the application:


aapt tool failed:/private/var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/037f8edf-077f-4ce0-931d-54ed25c7f6cb/com.facebook-res/values/values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.

/private/var/folders/tc/7bhn9rrn6fv4zr46rfbk5hb40000gn/T/037f8edf-077f-4ce0-931d-54ed25c7f6cb/com.facebook-res/values/values.xml:136: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.

Can please help advice, I am using Facebook ANE (http://www.myflashlabs.com/product/facebook-ane-adobe-air-native-extension) as well. Thank you

**Comment by myflashlab** [comment]
Ok, as it seems Facebook needs the full version of the AndroidStudio and the removed appcomptV7 in the lite version can't be used. On the other hand, the slow startup time on the barcode scanner is caused with that library. 🤔 This is something originated in the appcomptV7 library. anyhow, we will start an investigation on this to see if we can find a workaround. Thanks for the input.

**Comment by hengway1989** [comment]
Thank you, hope get your reply in soon.

**Comment by myflashlab** [comment]
We could not find a fix for this! at least not in a short notice. we will keep an eye on this anyhow for future but as for now, there's a good workaround you can use if you update the ANE to the latest version we released a few hours ago. Update to V3.4.0 and use the ```.warmup()``` method.

more information here: https://github.com/myflashlab/barcode-ANE/blob/master/AIR/src/MainFinal.as#L193-L208
