### ISSUE TITLE
Using the ANE in ViewNavigatorApplication

### ISSUE THREAD

**Issue by makanmel** [myflashlab/barcode-ANE#48]
First thank you for the library.
I have tried running your complete AS3 demo project and it works as expected. However when I tried to integrate it to my application that is build with Flex framework and uses ViewNavigatorApplication main class nothing is shown after you hit the "OK" button in the dialog:

```
<s:View xmlns:fx="http://ns.adobe.com/mxml/2009" xmlns:s="library://ns.adobe.com/flex/spark"
        destructionPolicy="never" actionBarVisible="true" title="Scan">
...
		private var barcode:Barcode;

		private function startScan():void
		{
			barcode = new Barcode();
			barcode.addEventListener(BarcodeEvent.RESULT, function (event:BarcodeEvent):void
			{
				result.text = event.param.data;
			});
			barcode.addEventListener(BarcodeEvent.CANCEL, cancel);

			barcode.open([Barcode.PDF417]);
		}
...
<s:TextArea id="result" />

```

Are the extra libraries (Feathers, Starling) required?

**Comment by Formability** [comment]
+1, We are also having the same issue.

**Comment by makanmel** [comment]
I was finally able to resolve the issue.
You need to add four ANEs (androidSupport, barcodeExtension, overrideAir and permissionCheck), use correct template (XML file) and correct init sequense as in the demo project.

**Comment by Formability** [comment]
I have all the supporting ANE's included and the correct XML and copied the sequence from the demo project but this istill isn't working on an iPhone 5.  I'll try it on an Android device later this week.

**Comment by myflashlab** [comment]
@Formability please give us more information on your tests/environment. As we are not experiencing any problem.

**Comment by Formability** [comment]
Were using Flash Builder 4.7 with Flex 4.6 and Air 26.  I have included all the needed ANEs (androidSupport, barcodeExtension, overrideAir and permissionCheck) (Except the Android support on iOS).
Below is the code I'm trying to use.

<?xml version="1.0" encoding="utf-8"?>
<os:OSView xmlns:fx="http://ns.adobe.com/mxml/2009"
		   xmlns:s="library://ns.adobe.com/flex/spark" title="Barcode"
		   xmlns:os="com.formability.myapp.*" creationComplete="createComplete()" >

	<fx:Script>
		<![CDATA[
			
			import com.myflashlab.air.extensions.barcode.Barcode;
			import com.myflashlab.air.extensions.barcode.BarcodeEvent;
			import com.myflashlab.air.extensions.nativePermissions.PermissionCheck;

			private var _ex:Barcode;
			private var _exPermissions:PermissionCheck = new PermissionCheck();
			
			protected function createComplete():void
			{
				checkPermissions();			
			}
			
			private function checkPermissions():void
			{
				// first you need to make sure you have access to the Camera if you are on Android?
				var permissionState:int = _exPermissions.check(PermissionCheck.SOURCE_CAMERA);
				
				if (permissionState == PermissionCheck.PERMISSION_UNKNOWN || permissionState == PermissionCheck.PERMISSION_DENIED)
				{
					_exPermissions.request(PermissionCheck.SOURCE_CAMERA, onRequestResult);
				}
				else
				{
					runmain();
				}
				
				function onRequestResult($state:int):void
				{
					if ($state != PermissionCheck.PERMISSION_GRANTED)
					{
						trace("You did not allow the app the required permissions!");
					}
					else
					{
						runmain();
					}
				}
			}
			
			private function runmain():void
			{
				// initialize the extension
				_ex = new Barcode();
				_ex.addEventListener(BarcodeEvent.RESULT, onResult);
				_ex.addEventListener(BarcodeEvent.CANCEL, onCancel);
				trace("running main");
				if(_ex.os == Barcode.ANDROID)
				{
					_ex.warmup();
				}
				
				if (_ex.isSupported())
				{
					trace("opening camera");
					_ex.open(null, null, true, "Cancel/ Back");
				}
				else
				{
					trace("isSupported: ", _ex.isSupported());
				}				
			}
			
			private function onCancel(e:BarcodeEvent):void
			{
				trace("scan canceled");
			}
			
			private function onResult(e:BarcodeEvent):void
			{
				trace("type is: ", e.param.type);
				trace("data is: ", e.param.data);
			}
		]]>
	</fx:Script>
	
</os:OSView>

Any help or suggestions would be appreciated.

**Comment by makanmel** [comment]
@Formability 

Try instantiating the Barcode when you declare it:

private var _ex:Barcode = new Barcode();
private var _exPermissions:PermissionCheck = new PermissionCheck();

**Comment by Formability** [comment]
Thank you for your help.
I have tried that and it is still behaving the same.  I have also tested it on an Android device and its the same problem.
I enabled the debugger and here is the output from the console.

running main
opening camera
BarcodeANE(BaseClassBarcode) openCamera started...
BarcodeANE(BaseClassBarcode) openCamera finished

The camera appears to start and then stop immediately. This is being tested on an iPhone 5 and a Google Nexus. 
Your thoughts would be appreciated.

**Comment by makanmel** [comment]
I use next code:

```
private var barcode:Barcode = new Barcode();
private var permission:PermissionCheck = new PermissionCheck();

private function initializeHandler(event:FlexEvent):void{
	var permissionState:int = permission.check(PermissionCheck.SOURCE_CAMERA);
	if (permissionState == PermissionCheck.PERMISSION_UNKNOWN || permissionState == PermissionCheck.PERMISSION_DENIED){
		permission.request(PermissionCheck.SOURCE_CAMERA, function ($state:int):void{
			if ($state != PermissionCheck.PERMISSION_GRANTED)
			{
				Alert.show("Permissions error");
				scanButton.enabled = false;
			}
		});
	}
}
private function onScanButtonClick(event:MouseEvent):void{
	if (barcode.isSupported()){
		barcode.addEventListener(BarcodeEvent.RESULT, function (event:BarcodeEvent):void{
			trace("Raw data:", event.param.data);
		});
		barcode.open([Barcode.PDF417]);
	}
}
...
```
If you still having issues with similar code then possibly you are having something wrong in the template XML file.

**Comment by Formability** [comment]
@makanmel Thank you for your help.  It is workig with your code.  I'm not sure why it still won't work with my code but I can now progress so thank you.

**Comment by myflashlab** [comment]
@Formability Your code does not work maybe because of this: https://github.com/myflashlab/barcode-ANE/issues/49#issuecomment-332832214

**Comment by Formability** [comment]
@myflashlab I used @makanmel code and its working OK now. Thanks
