### ISSUE TITLE
Barcode scanning not working with IOS

### ISSUE THREAD

**Issue by justAnotherprogramWriter** [myflashlab/barcode-ANE#49]
## Environment ##
* iOS Version: 9.3.5
* AIR SDK Version: 27

## Problem Description ##
Just downloaded the free version of Barcode ANE to try it out, and it works wonderfully in Android when I did a debug test via USB from Flash Builder 4.7. However, when I tried to test it out on my IPad for IOS, but it never get to the part where the camera is activated for scanning.

I did not want any beep sound, non did I want any vibration, so I set them to null and false respectively. I have been using the paid version of PermissionCheck ANE for all the permissions I required and I will paste some parts of my manifest xml below:

 ```
<iPhone>
         <InfoAdditions><![CDATA[
			<key>UIDeviceFamily</key>
			<array>
				<string>1</string>
				<string>2</string>
			</array>
			<key>NSAppTransportSecurity</key>
			  <dict>
			  <key>NSAllowsArbitraryLoads</key><true/>
			 </dict>			 
			<key>UIApplicationExit sOnSuspend</key><true/>
			
			<key>NSCameraUsageDescription</key>
			<string>For QR Code Scan</string>			
			
			<key>NSMicrophoneUsageDescription</key>
			<string>For Speech Recognition</string>
			
			<key>NSCalendarsUsageDescription</key>
			<string>For App to work properly</string>			
			
			<key>NSContactsUsageDescription</key>
			<string>For App to work properl</string>
		]]></InfoAdditions>
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>

<extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
    	
    <extensionID>com.myflashlab.air.extensions.barcode</extensionID>
    </extensions>
```

Please advice me on how to resolve this.

**Comment by justAnotherprogramWriter** [comment]
Ok, I acutally messed around with the order and the timing of the code and managed to get it to work. Still I am curious as to why Method 1 will not work.

METHOD 1:
```
private function init():void
{
	// initialize the extension
	_ex = new Barcode();
	_ex.addEventListener(BarcodeEvent.RESULT, onResult);
	_ex.addEventListener(BarcodeEvent.CANCEL, onCancel);
	if (_ex.isSupported())
	{		
		_ex.open(null, null, true, "back to The Air APP! :D");
	}	
}
```

Apparently, when I call open right after I initialize it and add the listener, the camera will not be triggered and the scanning will not start, however, if I go for method 2 below:

METHOD 2:

```
private function init():void
{
	// initialize the extension
	_ex = new Barcode();
	_ex.addEventListener(BarcodeEvent.RESULT, onResult);
	_ex.addEventListener(BarcodeEvent.CANCEL, onCancel);
	
       btn_var.addEventListener(MouseEvent.CLICK,on_click_function);	
}
private function on_click_function(e:MouseEvent):void
{
	if (_ex.isSupported())
	{		
		_ex.open(null, null, true, "Cancel");
	}	
}
```

Method 2 actually work great. Anyone has any idea why is that the case?

**Comment by myflashlab** [comment]
Oh, yes, that is exactly the problem. as mentioned here: https://github.com/myflashlab/barcode-ANE#asdoc

> NOTICE: the demo ANE works only after you hit the "OK" button in the dialog which opens. In your tests make sure that you are NOT calling other ANE methods prior to hitting the "OK" button.

**Comment by justAnotherprogramWriter** [comment]
O gosh. I can't believe I complete miss that part. Thanks.
