### ISSUE TITLE
Compiling with command line, how do I use the ane without the actionscript source?

### ISSUE THREAD

**Issue by nospaceleftondevice** [myflashlab/barcode-ANE#5]
import com.doitflash.air.extensions.barcode.Barcode;
import com.doitflash.air.extensions.barcode.BarcodeEvent;

Above lines fail because I have no source, how do i get past this?  Can i convert the library.swf to a .swc?

Note:  I'm not using any IDE, I compile and package via the commandl ine tools

**Comment by myflashlab** [comment]
I think if you implement the .ane file, the compiler should find those classes
