### ISSUE TITLE
android:theme in barcode-ANE

### ISSUE THREAD

**Issue by justAnotherprogramWriter** [myflashlab/barcode-ANE#50]
## Environment ##
* AIR SDK Version: 27

## Problem Description ##
I am not sure if this is the place to ask this question but I have a situation here. I am using the unpaid version of the ane and I have a default android theme that display a background with the following code in the style.xml

```
 <style name="Theme.NoShadow" parent="android:style/Theme.NoTitleBar">        
      <item name="android:background">@drawable/my_splash</item>
  </style>	
```

Every time when I run the below code for initialization:

```
if(_ex == null)
{
   _ex = new Barcode();
   _ex.addEventListener(BarcodeEvent.RESULT, bar_code_status_function);
   _ex.addEventListener(BarcodeEvent.CANCEL, bar_code_status_function);					
}
```

that background I set in the style will pop out, covering my whole screen, then after awhile, the actual scan camera will open up. When I hit the back button to close the scan, it will return to that background covering the whole screen again. I tried messing around with the android:theme on the activities listed in the Android Manifest xml, but it is just not working. My question is, besides the three activities we need to include for the barcode to work, are there somewhere in the ane that trigger any other activity that uses default style or theme? If there is, is there a way for me to edit that? If not? Is there any suggestion or solution to this? Below is the three activities included in my manifest for the barcode scan to work:

```
              <activity>
                <intent-filter>
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
                <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <category android:name="android.intent.category.DEFAULT" />
                </intent-filter>
            </activity>

            <activity android:name="com.google.zxing.client.android.CaptureActivity"
                android:clearTaskOnLaunch="true"
                android:screenOrientation="landscape"
                android:configChanges="orientation|keyboardHidden"
                android:stateNotNeeded="true"
                android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
                android:windowSoftInputMode="stateAlwaysHidden" />

            <activity android:name="com.doitflash.barcode.utils.ExBridge" />
```

**Comment by justAnotherprogramWriter** [comment]
Upon more testing and messing around, I found that my splash screen as actually used as the style of the dialogue box that says "ANE DEMO VERSION" with the okay button after i shrink the splash screen size. Is it ok for me to assume that if I use the paid version, this problem will not happen since there should not be a dialogue pop up?

**Comment by myflashlab** [comment]
you said you are using the paid version of the ANE, so you must not have the demo dialog to begin with...

Anyway, I had difficulties imagining the window problem you described. will you be able to record a video from what is happening?

Also tell me if you are seeing a similar result when running the [demo apk file](https://github.com/myflashlab/barcode-ANE/blob/master/demo.apk)?

**Comment by justAnotherprogramWriter** [comment]
Sorry! I mean UNPAID! So sorry. Anyway, I bought the paid version just now, and without the dialog box this problem did not occur. I am now almost 100 percent sure the dialog box does use the theme I applied for my project as the default theme. If you are still interest to see a video of it with the demo version, I can post it here next week.

O and sidetrack a bit, I would like to ask, is there anyway to speed up the warmup process? In the mist of warming up, I actually placed a loading bar, but the load bar animation will freeze when the warmup is happening.

**Comment by myflashlab** [comment]
Yes, I do like to see the video cast from what you experienced. And about the warm up process, there is not much we can do. We even tried to make it happen in a background thread but it didn't help. We are hoping this will be fixed in future versions of Google Play Dependencies.

**Comment by justAnotherprogramWriter** [comment]
I had prepared some screen records on how different conditions triggered the above problem in the links below. Please do take a look at them.

Overall Enviroment: Adobe Air 27, Captive Runtime
Splash Screen in PNG: A white bg with colorful text "MidiEnglish Primary" only

1. PAID ANE with full size splash screen:
[(https://www.dropbox.com/s/7bmv0ov1ku4clyn/paidane_fullscreenss.mp4?dl=0)]

2. UNPAID ANE with full size splash screen:
[https://www.dropbox.com/s/2yqac7bz4wwtyb4/unpaidane_fullscreenss.mp4?dl=0]

3. UNPAID ANE with small size splash screen (I actually used a different splash screen for this instead of the usual white one for the other three videos):
[https://www.dropbox.com/s/58y5fe166ixbgcr/unpaidane_smallss.mp4?dl=0]

4. UNPAID ANE without splash screen:
[https://www.dropbox.com/s/0x67x9ch5wn4tor/unpaidane_withoutss.mp4?dl=0]
