### ISSUE TITLE
Back button on Android

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/barcode-ANE#51]
We really need to have back button on Android (like on iOS).
Is it possible to add it now somehow?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
