### ISSUE TITLE
Can't get up and running in Animate CC.. tons of errors.

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/barcode-ANE#52]
I purchased the commercial version of this and am having issues. 

Do you have an Animate CC working example ?  The code examples I've tried do not work. All dependencies are there. 

Any guidance would be appreciated.

**Comment by trinoo1979** [comment]
Hello, did you solve your issue? Did you get it to work? I'm now facing the same problem...Animate CC and a lot of errors when try to debug on mobile device...any help would by appreciated.

**Comment by myflashlab** [comment]
Please let us know what error messages you are seeing, so we can better help. Thanks.

**Comment by trinoo1979** [comment]
Hello, thanks guys for your response a sorry for a delay. I know, that there is nothing wrong with your ANEs, its just a lack of knowledge on my side - as I am not new to AS3, but completely new to mobile development. The only thing I try to achieve here is just set up your barcode demo in Animate CC. So I downloaded all your AS3 demo files repository, set up basic scene, put all 4 ANEs (androidSupport-V27.0.2-lite.ane, barcodeExtension.ane, overrideAir.ane, permissionCheck.ane) to its place (and set up them in AS3 settings). But everytime I try to publish and test directly in my mobile device (Xperia, Android 4.4) I end up with this bunch of errors: http://trinoo.cz/animatecc_errors.gif

**Comment by trinoo1979** [comment]
Sorry, my hand was faster then my head...just wanted to add, that any simple sample Flash (or Animate) file would be great. A also dowloaded and watched your video tutorial (How to implement an ANE into your project using FlashCC") a few times, but still no able to get it to work here. Sorry guys for this lama questions..

**Comment by myflashlab** [comment]
@trinoo1979 Not at all, please feel free to ask any questions, we're here to help. Ok, there first thing I would suggest is to use the latest AIR SDK. have you tried compiling with AIR 29+?

**Comment by trinoo1979** [comment]
OK, got it to work (changed a few things including AIR SDK to v. 29). thanks :-)

**Comment by Orblord** [comment]
We are having similar issues in animate after updating to 29. After we run the barcode scanner none of our touch or click events will fire

**Comment by myflashlab** [comment]
@Orblord are you seeing any error messages? we are not seeing any problem like the one you mentioned.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
