### ISSUE TITLE
ANE changes app name to "Barcode Scanner" on devices with locale other than EN

### ISSUE THREAD

**Issue by Constans** [myflashlab/barcode-ANE#53]
My app name is changed to "Barcode Scanner" on devices with the locale set to anything other than EN.

As far as I've inspected it takes its name from localised xmls located in barcodeExtension.ane!/META-INF/ANE/Android-ARM/com.myflashlab.air.extensions.barcode-res/values/
barcodeExtension.ane!/META-INF/ANE/Android-ARM/com.myflashlab.air.extensions.barcode-res/values-ro/
barcodeExtension.ane!/META-INF/ANE/Android-ARM/com.myflashlab.air.extensions.barcode-res/values-hu/

Setting localised names for the app in the app config xml does not override this.

To reproduce create a simple app with a name other than "Barcode Scanner" then make sure the device you're testing on has default language set to let's say HU (Magyar) or RO (Romanian) and you'll be able to reproduce the issue I mentioned above. 

This is a very unpleasant and serious bug. I've delivered an app just to find out that on several users that my client had the name of the app is Barcode Scanner. :)

Any solutions? Thank you in advance!

**Comment by divlaine** [comment]
Im using this ANE with RU supportedLanguage, and have no such problem.

**Comment by Constans** [comment]
Try switching the phone's default language to Magyar or Romanian and will be able to replicate. The app name will become "Barcode Scanner".

Please confirm, if possible. 

Thank you!

**Comment by Constans** [comment]
Found a post that relates this issue with the integrated zxing library:
https://damianflannery.wordpress.com/2011/06/13/integrate-zxing-barcode-scanner-into-your-android-app-natively-using-eclipse/#comment-61 
My latest update for barcode scanner ANE is Aug 24, 2017 and for that version the above issue is occuring.

**Comment by myflashlab** [comment]
Ok, it seems like a problem with locale resource files. @Constans you can easily add/delete/modify the resource files using the resource manager tool. Install the [ANELAB](https://github.com/myflashlab/ANE-LAB/) and from the menu, open the ```Resource Manager``` window. there drag&drop the ANE into the window. Then you will be able to see all the resources which you can add/delete/modify and then re-package the ANE and test it to see how the problem will be fixed. Let us know how it goes.

**Comment by Constans** [comment]
I confirm that this fixed my issues.
You might consider to exclude in the main build the locale resource files or de-prioritize them,  as for I was unable to overwrite them with in-app description file / locale name setting. 
Almost all users that test in EN an app and have users with other locale (of the affected ones) will have their apps renamed to "Barcode Scanner".
Thank you for the assistance!

**Comment by myflashlab** [comment]
good to know this is fixed. We will be releasing a new version quickly.

**Comment by myflashlab** [comment]
Please test and confirm if this quick fix is working correctly on your side also?
[barcode.ane.zip](https://github.com/myflashlab/barcode-ANE/files/1702596/barcode.ane.zip)

**Comment by Constans** [comment]
I managed to confirm the fix on a test project.  Thank you!
