### ISSUE TITLE
silver version of the bar code extension giving me error but free one works without any problems

### ISSUE THREAD

**Issue by mikolajdebowski** [myflashlab/barcode-ANE#54]
Hi I used your guys extension for bar code scanner and the free one works great but have water mark so I decided purchase just now the silver version and getting error when try to initiate barcode scanner class

[Fault] exception, information=TypeError: Error #1006: value is not a function.
at com.myflashlab.air.extensions.barcode::Barcode()

can I get another one working like a free one but without watermark?

**Comment by myflashlab** [comment]
the licensed ANE is exactly an copy of the free version with the "demo dialog" being removed. The above error message means that the ANE is not correctly implemented in your project. Please make sure you have correctly implemented the ANE and everything should work just fine.

**Comment by mikolajdebowski** [comment]
what are the required changes that need to be implemented? apart of changing on the ANE file itself? the free version works perfectly fine so I assume I have everything in place... then I change a file and it doesn't work can you tell me what further changes you are referring to?

**Comment by myflashlab** [comment]
Aha, the ```permissionCheck.ane``` is also need to be purchased. Maybe you are using the demo version of that ANE also. 

This is mentioned on the purchase page of the [barcode ANE](https://www.myflashlabs.com/product/qr-code-ane-adobe-air-native-extension/).
> Heads up! This ANE depends on the Permission Check ANE as its requesting for a permission on the Native API. You need to include this ANE beside the Permission Check ANE together to make it work properly in your AIR projects. Click here to learn more about the Permission Check ANE and its cool features!

**Comment by mikolajdebowski** [comment]
yep purchased other one and warnings went away all good... sorry for whole thread can be closed all working as expected and overall easy to use and configure... thank you for your help anyway
