### ISSUE TITLE
IOS not have barcode scanner aspect

### ISSUE THREAD

**Issue by dculebras** [myflashlab/barcode-ANE#55]
Hello, I'm using the version 3.4.4 Barcode ANE.

I have develope an application in AIR for Android and IOS plattforms.
Everything works fine, but the IOS barcode scanner don't show the scanner aspect.
I mean, the camera start, and read the barcode, but tdont show the red line and the picture frame, so looks like you are takeing a single photo. For my customers It is confusing.

The same problem occurs on Ipad and iPhone.

**Comment by myflashlab** [comment]
Well, I think your app should state why the camera is opening so users know they should scan a barcode. anyway, for custom jobs, you can always contact us through https://www.myflashlabs.com/contact/
