### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by etulfnap** [myflashlab/barcode-ANE#57]
Hi, 

It seems there were already requests to enhance Barcode-ANE, but it seems to have less priority than other projects or matters.  Most of items are mentioned below years ago, but just wanna say still there're users who eagerly waiting for some updates.

Here are things I wish to have.
1. Orientation change. (now is fixed to horizontal.   when App is auto rotation, sometimes camera mode opens up and rotate 90' or 180' each time.  
2. Flash light (please~ )
3. Continuous scan
4. Customize messaging while camera mode.  This will be useful if use want to show scanned items on the way while continuous scan mode.

Sorry to bring out competitor's ANE, but they have all  what I mentioned above.  Even can adjust autofocus timing interval.

http://distriqt.github.io/ANE-Scanner/asdocs/

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
