### ISSUE TITLE
Barcode ANE won't initalize in Flash CC

### ISSUE THREAD

**Issue by gtechman** [myflashlab/barcode-ANE#7]
Hello,
I am unable to get the barcode ANE to initialize upon publishing my app to a device. I am not experiencing any compiler errors and the only run-time error I get I believe is the one to be expected from running the extension in the simulator: " Error #3500: The extension context does not have a method with the name command." 

I have added the ANE and SWC to the project library. I also used the manifest supplied in your example. Additionally, I set the SWC files to compile externally. I am at a loss at to why it is not working. On the actionscript side I'm using your example. I attached my descriptor file, as it is the only thing I think could be messed up.
Thank you very much for your help!

[EMS PreAlert Manifest.txt](https://github.com/myflashlab/barcode-ANE/files/88489/EMS.PreAlert.Manifest.txt)

**Comment by myflashlab** [comment]
please check the following:
1) run on a real device not a simulator
2) make sure your Air SDK is above ```http://ns.adobe.com/air/extension/15.0``` update to the latest sdk which is 20 as right now and check that it is correctly specified in your air manifest .xml file
3) double check if your manifest .xml file includes the following
```xml
  <extensions>
    <extensionID>com.myflashlab.air.extensions.barcode</extensionID>
  </extensions>
```
4) check your compiler additional parameters if it has a -swf-version synced with your Air SDK. for example Air SDK 19 goes with -swf-version=30

5) and finally, if you are running on FlashDevelop or compiling on cammandline, make sure your packager adt command is finding the ane folder like (niotice ```-extdir lib/```)
```bat
call adt -package -target %TYPE%%TARGET% %OPTIONS% %SIGNING_OPTIONS% "%OUTPUT%" "%APP_XML%" %FILE_OR_DIR% -extdir lib/
```

**Comment by gtechman** [comment]
Thank you for your quick reply,
The AIR SDK version was vs 16.0 and was out of date. Updating it to 20 fixed the problem! For people looking to update their SDK in Flash CC go to the HELP menu and click and click MANAGE ADOBE AIR SDK.
