### ISSUE TITLE
Activity in portrait mode

### ISSUE THREAD

**Issue by savvie** [myflashlab/barcode-ANE#8]
There is a problem with the camera view, although it is rotated manually by setting the activity to portrait it won't scan until you turn it to landscape.

**Comment by myflashlab** [comment]
Please specify which platform you are experiencing this? and that would be great if you can help us duplicate this problem so we can see the problem and fix it.

**Comment by savvie** [comment]
I've tested on android 5.1.1 (Oneplus One) and android 4.4.2(Samsung Galaxy tab 3 8"). I will have to test it on an IOS device at some point but for now I have those 2. Flex SDK 4.14.1 and AIR 19.0

**Comment by myflashlab** [comment]
Could you also tell me if you have a similar problem when running the demo
.apk we have on our repository?

On Friday, February 5, 2016, savvie <notifications@github.com> wrote:

> I've tested on android 5.1.1 (Oneplus One) and android 4.4.2(Samsung
> Galaxy tab 3 8"). I will have to test it on an IOS device at some point but
> for now I have those 2. Flex SDK 4.14.1 and AIR 19.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/barcode-ANE/issues/8#issuecomment-180261089>
> .
>


-- 
Sent from iPhone

**Comment by myflashlab** [comment]
Please update us about this problem. Thanks.

**Comment by gorjan** [comment]
I have the same problem. My app is always in portrait mode. AutoOrient is set to false.
I changed the following values from landscape to portrait.
```<uses-feature android:name="android.hardware.screen.portrait" />```
and
```android:screenOrientation="portrait" ```

I recorded a screen cast video so you can see what exactly is happening. Here is the [link](https://drive.google.com/file/d/0B_97B2gs38ZDMG9jTkY0V21jZGM/view?usp=sharing).

**Comment by savvie** [comment]
Hello I'm the op, the problem still persists, I'm sorry I haven't done any updates on the issue it's just the idea was adandoned but it seems that we are going to do it, gorjan could you please open a new activity on the matter?

**Comment by myflashlab** [comment]
refer to this issue: https://github.com/myflashlab/barcode-ANE/issues/12
