### ISSUE TITLE
Error #1009 in Fash CC Pro

### ISSUE THREAD

**Issue by ckpsde** [myflashlab/barcode-ANE#9]
![screenshot 2016-02-17 11 10 42](https://cloud.githubusercontent.com/assets/17204839/13106285/ad8c41e2-d567-11e5-8adc-9e3477b1bb12.png)
Hi There!
I’m very much interested in your fantastic Barcode ANE. I tried to test it in my app but did not get it to work.
I work with Fash CC Pro.

###################
I added your barcodeExtension.ane in my AS3 Settings. I added your sample-AS3-code to my project 

var _ex:Barcode = new Barcode();
_ex.addEventListener(BarcodeEvent.RESULT, onResult);
_ex.addEventListener(BarcodeEvent.CANCEL, onCancel);
…

###################
I added your sample code to my application.xml

<uses-permission android:name="android.permis…
<extensionID>com.myflashlab.air.extensions.barcode</extensionID>
...

###################
But:
Debugger says:
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.barcode.android::Android()
	at com.myflashlab.air.extensions.barcode::Barcode()
	at PraxisApp_fla::container_mc_2/frame5()[PraxisApp_fla.container_mc_2::frame5:8]
	at flash.display::MovieClip/gotoAndStop()
	at Function/PraxisApp_fla:container_mc_2/TransIn/PraxisApp_fla:onFinishScaleX()[PraxisApp_fla.container_mc_2::frame1:94]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at fl.transitions::Tween/set time()
	at fl.transitions::Tween/nextFrame()
	at fl.transitions::Tween/onEnterFrame()
Quellcode kann an dieser Stelle nicht angezeigt werden.

###################
What did I wrong?
Thank you very much for your help!
Christoph

**Comment by myflashlab** [comment]
Would you please give us the exact error message you are receiving? What the error says?

**Comment by ckpsde** [comment]
Thank you for your reply!

Here is the console error message:
#########################################
Player stellt Verbindung her. Bitte warten ...
[SWF] PraxisApp.swf - 418244 Byte nach Dekomprimierung
Haltepunkt wurde nicht gesetzt; kein ausführbarer Code in Zeile 22 von Szene 1, Ebene 'action', Bild 1
TypeError: Error #1009: Cannot access a property or method of a null object reference.
               at com.myflashlab.air.extensions.barcode.android::Android()
               at com.myflashlab.air.extensions.barcode::Barcode()
               at PraxisApp_fla::container_mc_2/frame5()[PraxisApp_fla.container_mc_2::frame5:8]
               at flash.display::MovieClip/gotoAndStop()
               at Function/PraxisApp_fla:container_mc_2/TransIn/PraxisApp_fla:onFinishScaleX()[PraxisApp_fla.container_mc_2::frame1:94]
               at flash.events::EventDispatcher/dispatchEventFunction()
               at flash.events::EventDispatcher/dispatchEvent()
               at fl.transitions::Tween/set time()
               at fl.transitions::Tween/nextFrame()
               at fl.transitions::Tween/onEnterFrame()
Quellcode kann an dieser Stelle nicht angezeigt werden.
#########################################

This is my AS3-code:
#########################################
stop();
Scan_Back_btn               .addEventListener(MouseEvent.CLICK, MainButtonBack);

import com.myflashlab.air.extensions.barcode.Barcode;
import com.myflashlab.air.extensions.barcode.BarcodeEvent;
import flash.filesystem.File;

var _ex:Barcode = new Barcode();
_ex.addEventListener(BarcodeEvent.RESULT, onResult);
_ex.addEventListener(BarcodeEvent.CANCEL, onCancel);

function ScanCode(e:Event):void{
               if (_ex.isSupported()){
                              code_txt.text = "Please wait...";
                              //to read only the selected barcode types. use an array to read one or more barcodes
                              _ex.open([Barcode.QR], File.applicationDirectory.resolvePath("com_doitflash_barcode_beep.mp3"), true, "Cancel");
                              // to read all barcodes supported by the extension. read documentations to know which barcodes are supported.
                              //_ex.open(null, File.applicationDirectory.resolvePath("com_doitflash_barcode_beep.mp3"), true, "Cancel");
               } else {
                              code_txt.text = "isSupported: " + _ex.isSupported();
               }
}

function onCancel(e:BarcodeEvent):void {
    trace("scan canceled")
}

function onResult(e:BarcodeEvent):void {
    trace("type is: ", e.param.type)
               trace("data is: ", e.param.data);
               code_txt.text = e.param.data.toString();
}

scanANE_btn.addEventListener(MouseEvent.CLICK, ScanCode);
#########################################

Thank you for your help!

Best Regards
Christoph

Von: myflashlab [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. Februar 2016 09:32
An: myflashlab/barcode-ANE <barcode-ANE@noreply.github.com>
Cc: ckpsde <christoph.kossack@parostatus.de>
Betreff: Re: [barcode-ANE] Error #1009 in Fash CC Pro (#9)


Would you please give us the exact error message you are receiving? What the error says?

**Comment by myflashlab** [comment]
Well, as the error message shows, you are either testing on a simulator, which you shouldn't or the ANE has not been correctly embedded into the project yet.

**Comment by ckpsde** [comment]
Thank you for your reply. I was testing on a Samung i9300. So how can I embed the ANE correct? I have attached a  screenshot to show you the way I embedded the ANE. What did I wrong?

Best Regards
Christoph


Von: myflashlab [mailto:notifications@github.com]
Gesendet: Freitag, 19. Februar 2016 14:08
An: myflashlab/barcode-ANE <barcode-ANE@noreply.github.com>
Cc: ckpsde <christoph.kossack@parostatus.de>
Betreff: Re: [barcode-ANE] Error #1009 in Fash CC Pro (#9)


Well, as the error message shows, you are either testing on a simulator, which you shouldn't or the ANE has not been correctly embedded into the project yet.

**Comment by myflashlab** [comment]
You might find the below screenshot helpful?
![01](https://cloud.githubusercontent.com/assets/1692948/13246983/2c493a76-da2c-11e5-9f64-748b561500df.jpg)

**Comment by ckpsde** [comment]
Thank you very much for your help. Sadly, it didn’t work. The ANE was included automaticly by flash cc. I added it manually on top – just to be sure. But the compiler throws the same #1009 error.

What else can it be?

Best regards
Christoph

Von: myflashlab [mailto:notifications@github.com]
Gesendet: Dienstag, 23. Februar 2016 10:22
An: myflashlab/barcode-ANE <barcode-ANE@noreply.github.com>
Cc: ckpsde <christoph.kossack@parostatus.de>
Betreff: Re: [barcode-ANE] Error #1009 in Fash CC Pro (#9)


You might find the below screenshot helpful?
[01]<https://cloud.githubusercontent.com/assets/1692948/13246983/2c493a76-da2c-11e5-9f64-748b561500df.jpg>

**Comment by ckpsde** [comment]
Dear Sir or Madam,

do you have any idea?

In the mean time I tested my app with your ANE on an iPhone. It works perfectly fine there with exactly the same code.

So it seems there is anything wrong in the air.extentions.barcode.android. Your test app „QR Code“ works fine on the Android phone. What can it be? It is a Samsung GT-I9300. Android-Version 4.3.

Best Regards
Christoph


Von: Dr. Christoph K.-H. Kossack
Gesendet: Mittwoch, 24. Februar 2016 11:48
An: 'myflashlab/barcode-ANE' <reply@reply.github.com>
Betreff: AW: [barcode-ANE] Error #1009 in Fash CC Pro (#9)

Thank you very much for your help. Sadly, it didn’t work. The ANE was included automaticly by flash cc. I added it manually on top – just to be sure. But the compiler throws the same #1009 error.

What else can it be?

Best regards
Christoph

Von: myflashlab [mailto:notifications@github.com]
Gesendet: Dienstag, 23. Februar 2016 10:22
An: myflashlab/barcode-ANE <barcode-ANE@noreply.github.com<mailto:barcode-ANE@noreply.github.com>>
Cc: ckpsde <christoph.kossack@parostatus.de<mailto:christoph.kossack@parostatus.de>>
Betreff: Re: [barcode-ANE] Error #1009 in Fash CC Pro (#9)


You might find the below screenshot helpful?
[01]<https://cloud.githubusercontent.com/assets/1692948/13246983/2c493a76-da2c-11e5-9f64-748b561500df.jpg>

**Comment by myflashlab** [comment]
Also note that Flash CC is sometimes a bit bugy when generating the manifest .xml file even though you might have set it to manual mode. so before you compile your project, make sure that the manifest is set correctly while comparing it to our [demo xml file](https://github.com/myflashlab/barcode-ANE/blob/master/FD/application.xml).

**Comment by myflashlab** [comment]
especially this part
```xml
  <extensions>
    <extensionID>com.myflashlab.air.extensions.barcode</extensionID>
  </extensions>
```

and also make sure you are using the latest Air SDK version.

**Comment by ckpsde** [comment]
Thank you for your reply!

The lines were in the manifest.xml but it worked only on iOS – not android.
It seems to be a problem with flash cc / AIR 17. After updating to animate cc / AIR 20 everything works fine – without changing a single line in the project or the manifest.

Thank you and best regards
Christoph

Von: myflashlab [mailto:notifications@github.com]
Gesendet: Samstag, 27. Februar 2016 06:16
An: myflashlab/barcode-ANE <barcode-ANE@noreply.github.com>
Cc: ckpsde <christoph.kossack@parostatus.de>
Betreff: Re: [barcode-ANE] Error #1009 in Fash CC Pro (#9)


especially this part

  <extensions>

    <extensionID>com.myflashlab.air.extensions.barcode</extensionID>

  </extensions>

and also make sure you are using the latest Air SDK version.
